In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
# Vertical sum

cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
# Percentage

percentage = 100*A/cal

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
# Broadcasting real number with 1D vector

a = np.array([1,2,3,4])
b = a + 100

print(b)

[101 102 103 104]


In [8]:
# Broadcasting 1D vector with 2D vector

a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([100, 200, 300])
c = a + b

print(c)

[[101 202 303]
 [104 205 306]]


In [10]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

print(c)

[[ 0.03681135  0.42478419 -1.7796569 ]
 [-0.01688295 -0.03340209 -0.03266932]
 [-1.05635436  1.09421886  0.93850687]]
